services:
  api:
    image: ghcr.io/tylerqube/palapi:latest
    env_file:
      - .env.api
    ports:
      - "3030:3030"
    environment:
      - NODE_ENV=production
      - DB_URL=mongodb://mongo:27017/palpoll
    depends_on:
      - mongo

  client:
    image: ghcr.io/tylerqube/palpoll:latest
    ports:
      - "8080:80"

  mongo:
    image: mongo:noble
    container_name: palpoll-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
